---
title: "STAT 405 - Project Proposal"
output:
  pdf_document: default
  html_document: default
---

# Team

Joseph Lardner-Burke - 44848893

Karn Shoker - 59310094

**Repo:** <https://github.com/kshoker12/STAT_405_Project>

# Datasets

**Main:**

**Backup:**

# Scientific Question

**Main Research Question:** Infer a student's ability to do algebra problems based on their test performance, measuring the observed question, the student's answer, and the time to complete question.

**Motivation**: We chose this research question because inference questions such as this are the core for automatic tutoring systems which have to make real-time inference to assist students and recommend catered problems to allow student to improve. We are both interested in potentially making a tutoring system so exploring this research question can give us the insights and develop knowledge in Bayesian Inference to one day develop this.

# Methodology

The model structure

First we have

$\mu_j$ the mean abilities of a class to do skill $j\in \{+,-,\times,\div, \int,\frac{d}{dx}\}$ and $\sigma_i$ the standard deviation of the class at each of these abilities.

$$
\mu_{1,j} \sim N(0,1) 
$$

$$
\sigma_j \sim Exp(1)
$$

then the abilities of each individual student the $k$'th student will be $\alpha_{i,j,k}$

$$
\alpha_{i,j,k}|\mu_{1,j},\sigma_j,\alpha_{i-1,j,k} \sim N(\mu_{1,j} +\alpha_{i-1,j,k},\sigma_i^2)
$$

this update happens every test

we want the value of the individuals abilities to also vary relative to the group over time...

so when we initialize we have the initial distribution of abilities mean of the class and then i vary the individuals abilities can fluctuate over time

now we have a the steps in the problem

$S_{i,j,k,l}|S_{i,j^*,k,l-1},\alpha_{ijk} \sim Bern(S_l\cdot(logistic(\alpha_{ijk}-\frac{1}{t}))$

So to simplify this we will only consider 1 test.

Thus we will have a bunch of students and only one test for now.

We will perform this Bayesian inference using MCMC methods explored in class.

# Team Member Contributions

-   Equal distribution (roughly 50:50 split) across writing, data handling, coding, and analysis and we will split these tasks into phases and delegate specific tasks at the beginning of each phase.
-   Some tasks depend on others so we will coordinate regularly and have meetings early on.
-   We will use meaningful commit messages on GitHub for clarity and review each others commits regularly.

# Code headers

```{r}
# Load one candidate dataset
train_data <- read.csv("data/train_data/train_task_1_2.csv")

# Show the first 6 rows
head(train_data)

```

## Actual data set 

<https://dqanonymousdata.blob.core.windows.net/neurips-public/data.zip>

from <https://www.eedi.com/research>

## Backup data set 

<https://www.kaggle.com/competitions/eedi-mining-misconceptions-in-mathematics/data>
